<?php
/**
 * Created by PhpStorm.
 * User: heixiake
 * Date: 2018/4/13
 * Time: 4:54 PM
 */

class Person
{
    public $name;

    public function __construct($name)
    {
        $this->name = $name;
    }

    public function show()
    {
        echo "打扮的" . $this->name . "<br>";
    }
}

class Finery
{
    protected $person;

    public function decorate($person)
    {
        $this->person = $person;
    }

    public function show()
    {
        if ($this->person != null)
        {
            $this->person->show();
        }
    }
}

class TShirt extends Finery
{
    public function show()
    {
        echo 'T恤  ';
        parent::show(); // TODO: Change the autogenerated stub
    }
}

class BigTrours extends Finery
{
    public function show()
    {
        echo '大裤 ';
        parent::show();
    }
}

class Sneakers extends Finery
{
    function show()
    {
        echo '破球鞋 ';
        parent::show();
    }
}

class Suit extends Finery
{
    function show()
    {
        echo '西装  ';
        parent::show();
    }
}

class Tie extends Finery
{
    function show()
    {
        echo '领带 ';
        parent::show();
    }
}

class LeatherShoues extends Finery
{
    function show()
    {
        echo '皮鞋 ';
        parent::show();
    }
}


$sc = new Person("小菜");
echo "第一种打扮:<br>";

$sn = new Sneakers();
$bt = new BigTrours();
$ts = new Tshirt();

$sn->decorate($sc);
$bt->decorate($sn);
$ts->decorate($bt);


$bt->show();
echo "<br>";
$ts->show();


//$p = new Person('aaa');
//
//$sn = new Sneakers();
//$bt = new BigTrours();
//$ts = new Tshirt();
//
//$sn->decorate($p);
//$bt->decorate($sn);
//$ts->decorate($bt);
//
//$ts->show();

