<?php
/**
 * Created by PhpStorm.
 * User: heixiake
 * Date: 19/04/2017
 * Time: 10:54 AM
 */

namespace frontend\components;


use yii\base\Object;
use yii\db\Connection;

class MyClass extends Object
{
    public $prop1;
    public $prop2;
    public $age;
//    public $mail;
//    public function __construct(Mail $mail, array $config=['d'])
    public function __construct(Mail $mail, array $config=['prop1'=>'p1','prop2'=>'p2'])
    {
////        $this->age = $p1;
////        unset($config['prop1']);
//        $this->age = $mail;
        parent::__construct($config);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        $this->prop1='33';
    }

}