<?php
/**
 * Created by PhpStorm.
 * User: heixiake
 * Date: 06/04/2017
 * Time: 10:17 AM
 */

namespace frontend\panels;


use yii\base\Event;
use yii\base\View;
use yii\base\ViewEvent;
use yii\debug\Panel;

class ViewsPanel extends Panel
{
    private $_viewFiles = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Event::on(View::className(), View::EVENT_BEFORE_RENDER, function (ViewEvent $event){
            $this->_viewFiles[] = $event->sender->getViewFile();
        });
    }

    public function getName()
    {
        return "Views";
    }


    public function getSummary()
    {
        $url = $this->getUrl();
        $count = count($this->data);
        return "<div class=\"yii-debug-toolbar__block\"><a href=\"$url\">Views <span class=\"yii-debug-toolbar__label yii-debug-toolbar__label_info\">$count</span></a></div>";

    }

    public function getDetail()
    {
        return '<ol><li>' . implode('<li>', $this->data) . '</ol>';
    }

    public function save()
    {
        return $this->_viewFiles;
    }


}