<?php

namespace common\models;

use frontend\models\FamilyCar;
use frontend\models\SportCar;
use Yii;

/**
 * This is the model class for table "car".
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 */
class Car extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'car';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'type' => Yii::t('app', 'Type'),
        ];
    }

    public static function instantiate($row)
    {
        switch ($row['type']) {
            case SportCar::TYPE:
                return new SportCar();
            case FamilyCar::TYPE:
                return new FamilyCar();
            default:
                return new self();

        }
        return parent::instantiate($row); // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     * @return \common\models\query\CarQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CarQuery(get_called_class());
    }
}
