<?php

namespace common\models\query;

/**
 * This is the ActiveQuery class for [[\common\models\Car]].
 *
 * @see \common\models\Car
 */
class CarQuery extends \yii\db\ActiveQuery
{
    public $type;

    /*public function active()
    {
        return $this->andWhere('[[status]]=1');
    }*/

    /**
     * @inheritdoc
     * @return \common\models\Car[]|array
     */
    public function all($db = null)
    {
        return parent::all($db);
    }

    /**
     * @inheritdoc
     * @return \common\models\Car|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }

    /**
     * @param \yii\db\QueryBuilder $builder
     * @return \yii\db\Query
     */
//    public function prepare($builder)
//    {
//        if ($this->type !== null) {
//            $this->andWhere(['type'=>$this->type]);
//        }
//        return parent::prepare($builder); // TODO: Change the autogenerated stub
//    }
}
