<?php
/**
 * Created by PhpStorm.
 * User: heixiake
 * Date: 14/04/2017
 * Time: 4:00 PM
 */

namespace frontend\components;


use yii\base\ActionFilter;
use Yii;

class ActionTimeFilter extends ActionFilter
{
    private $_startTime;

    public function beforeAction($action)
    {
        $this->_startTime = time();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $time = time() - $this->_startTime;
        Yii::trace("Action '{$action->uniqueId}' spent $time second.");
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }


}