<?php
/**
 * Created by PhpStorm.
 * User: heixiake
 * Date: 13/04/2017
 * Time: 4:37 PM
 */

namespace frontend\components;


use yii\base\Widget;
use yii\helpers\Html;

class HelloWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->message == null){
            $this->message = "hello message";
        }
    }

    public function run()
    {
        return Html::encode($this->message);
    }


}