<?php
/**
 * Created by PhpStorm.
 * User: heixiake
 * Date: 2018/11/1
 * Time: 11:37 AM
 */

namespace frontend\components;


use yii\base\Component;
use yii\helpers\Html;

class MessageComponent extends Component
{
    public $content;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->content = "hello custom component in yii2";
    }

    public function display($content = null)
    {
        if ($content != null) {
            $this->content = $content;
        }

        echo Html::encode($this->content);
    }
}